import Config
config :ash, policies: [show_policy_breakdowns?: true]

# LiveDebugger binds its own endpoint on a fixed port (4007). A second Phoenix
# project running on the same machine therefore stops this one from booting at
# all: `:eaddrinuse` on a child of the supervision tree takes the whole app
# down, and the error names LiveDebugger rather than the port, so it reads like
# a broken dependency rather than a collision.
#
# `disabled?` rather than a port override because the port is not configurable —
# the endpoint's own config key only feeds the URLs it prints. Off by default,
# so the debugger is there as usual; set LIVE_DEBUGGER_DISABLED=1 to bring the
# relay up beside something else.
config :live_debugger, disabled?: System.get_env("LIVE_DEBUGGER_DISABLED") == "1"

# Configure your database
# Credentials default to the conventional postgres/postgres, but read the
# standard PG* variables first. devenv's Postgres creates a superuser named
# after the OS user and no `postgres` role at all, so the hardcoded pair fails
# with a bare `FATAL: role "postgres" does not exist` — surfaced through Ecto as
# "The database for Sync.Repo couldn't be created: killed", which names neither
# the role nor the cause.
config :sync, Sync.Repo,
  username: System.get_env("PGUSER") || "postgres",
  password: System.get_env("PGPASSWORD") || "postgres",
  hostname: System.get_env("PGHOST") || "localhost",
  port: String.to_integer(System.get_env("PGPORT") || "5432"),
  database: System.get_env("PGDATABASE_SYNC") || "sync_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sync, SyncWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "zsxY2Fk++LZoBvPcyzlmfgvJsJcNciGuxOAtW7Hxygt2eGVTW4Dzwe5pssAnNKRq",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:sync, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sync, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :sync, dev_routes: true, token_signing_secret: "0qce9li7h72qZ+jH3/z3AN59uef6O1Ne"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
