//! M1 gate, native half: prove a snapshot produced by a NATIVE peer carries the
//! content we expect, and publish those exact bytes as a committed fixture that
//! the JS half (`tests/js/interop.mjs`) loads and asserts against.
//!
//! The fixture is committed rather than generated at test time on purpose: the
//! point is to prove that bytes written by one implementation are readable by
//! the other. A fixture regenerated by whichever side is running would prove
//! nothing. Regenerate deliberately with `ROAM_REGEN_FIXTURE=1`.

use roam_wasm::Doc;
use std::path::PathBuf;

/// Canonical fixture content. `tests/js/interop.mjs` mirrors these constants —
/// they must be kept in lockstep, which is the whole point of the exercise.
const PEER_ID: u64 = 7;
const TEXT_ID: &str = "notes/hello.md";
const TEXT_BODY: &str = "hello from native";
const MAP_ID: &str = "meta";
const MAP_KEY: &str = "title";
const MAP_VALUE: &str = "Hello";

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/native_snapshot.loro")
}

/// Build the canonical document. Kept separate so regeneration and assertion
/// cannot drift apart.
fn canonical_doc() -> Doc {
    let doc = Doc::new(PEER_ID).expect("new doc");
    doc.insert_text(TEXT_ID, 0, TEXT_BODY).expect("insert text");
    doc.set_entry(MAP_ID, MAP_KEY, MAP_VALUE)
        .expect("set entry");
    doc.commit();
    doc
}

fn assert_canonical_content(doc: &Doc) {
    assert_eq!(doc.text(TEXT_ID), TEXT_BODY, "text container mismatch");
    assert_eq!(
        doc.get_entry(MAP_ID, MAP_KEY).as_deref(),
        Some(MAP_VALUE),
        "map entry mismatch"
    );
}

/// Pure behaviour of the façade type: a snapshot round-trips into a fresh doc
/// with a *different* peer id (the browser will always be a different peer).
#[test]
fn snapshot_round_trips_into_a_fresh_peer() {
    let snapshot = canonical_doc().snapshot().expect("snapshot");

    let fresh = Doc::new(PEER_ID + 1).expect("fresh doc");
    fresh.import(&snapshot).expect("import");

    assert_canonical_content(&fresh);
}

/// The committed fixture must still decode to the canonical content. This is
/// what the JS side independently asserts, so a break here and a break there
/// mean the same thing.
#[test]
fn committed_fixture_decodes_to_canonical_content() {
    let path = fixture_path();

    if std::env::var_os("ROAM_REGEN_FIXTURE").is_some() {
        let snapshot = canonical_doc().snapshot().expect("snapshot");
        std::fs::create_dir_all(path.parent().unwrap()).expect("create fixture dir");
        std::fs::write(&path, &snapshot).expect("write fixture");
    }

    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "fixture {} unreadable ({e}); regenerate with ROAM_REGEN_FIXTURE=1",
            path.display()
        )
    });

    let doc = Doc::new(999).expect("doc");
    doc.import(&bytes).expect("import fixture");
    assert_canonical_content(&doc);
}

/// The other direction, and the half that actually proves interop: these bytes
/// were produced by `loro` compiled to wasm and driven from JavaScript. If a
/// native peer can read them, the browser is a real replica and not a
/// lookalike. Regenerate with `tests/js/run.sh`.
#[test]
fn js_produced_fixture_decodes_to_canonical_content() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/js_snapshot.loro");

    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "JS fixture {} unreadable ({e}); regenerate with tests/js/run.sh",
            path.display()
        )
    });

    let doc = Doc::new(1234).expect("doc");
    doc.import(&bytes).expect("import JS fixture");

    assert_eq!(doc.text("notes/from-js.md"), "hello from javascript");
    assert_eq!(doc.get_entry("meta", "author").as_deref(), Some("browser"));
}
